# Fabric notebook source
# Horizon Books - Planning Schema & Table Setup
# Auto-generated by Deploy-Planning.ps1

import base64
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

b64_content = "__SQL_B64__"
sql_content = base64.b64decode(b64_content).decode('utf-8')

# Only execute CREATE SCHEMA and CREATE VIEW statements
# Table creation is handled by the PySpark populate notebook
statements = sql_content.split(';')
executed = 0
skipped = 0

print("=" * 60)
print("  Planning in Fabric IQ - Schema and View Setup")
print("=" * 60)

for i, stmt in enumerate(statements, 1):
    stmt = stmt.strip()
    lines = [l for l in stmt.split('\n') if l.strip() and not l.strip().startswith('--')]
    if not lines:
        continue
    # Skip CREATE TABLE statements — PySpark populate handles table creation
    stmt_lower = stmt.lower()
    if 'create table' in stmt_lower:
        skipped += 1
        continue
    try:
        spark.sql(stmt)
        executed += 1
        # Extract table/view name for logging
        for kw in ['CREATE TABLE', 'CREATE SCHEMA', 'CREATE OR REPLACE VIEW']:
            if kw.lower() in stmt.lower():
                name = stmt.lower().split(kw.lower())[-1].strip().split('(')[0].split(' as ')[0].strip()
                print(f'  OK  {kw}: {name}')
                break
    except Exception as e:
        skipped += 1
        print(f'  WARN Statement {i} skipped: {e}')

print(f"\nPlanning setup complete: {executed} succeeded, {skipped} skipped")

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }
