# Fabric notebook source
# Horizon Books - Planning Data Population
# Auto-generated by Deploy-Planning.ps1
#
# Reads forecast outputs + fact tables from Gold, generates planning
# targets with Base/Optimistic/Conservative scenarios, and writes to
# the planning schema.

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, lit, when, current_timestamp, date_format, trunc,
    sum as spark_sum, count, countDistinct, avg, round as spark_round,
    add_months, month as spark_month, year as spark_year
)
from pyspark.sql.types import *
import pandas as pd
import numpy as np
from datetime import datetime
from dateutil.relativedelta import relativedelta

spark = SparkSession.builder.getOrCreate()

# ── Configuration ──
PLANNING_HORIZON = 12
SCENARIOS = {"Base": 0.08, "Optimistic": 0.15, "Conservative": 0.03}
HC_GROWTH = {"Base": 0.05, "Optimistic": 0.10, "Conservative": 0.02}
VARIANCE_THRESHOLDS = {"favorable": 0.05, "critical": -0.15}
GENERATED_AT = datetime.utcnow()

spark.sql("CREATE SCHEMA IF NOT EXISTS planning")

# Drop any SQL-DDL-created empty tables to avoid type conflicts with PySpark Delta writes
for _t in ["PlanRevenueTargets", "PlanFinancialTargets", "PlanWorkforceTargets",
           "PlanVarianceAnalysis", "PlanScenarioSummary"]:
    spark.sql(f"DROP TABLE IF EXISTS planning.{_t}")

print("=" * 60)
print("  Planning in Fabric IQ - Data Population")
print("=" * 60)
print(f"  Horizon: {PLANNING_HORIZON} months")
print(f"  Scenarios: {list(SCENARIOS.keys())}")

def fiscal_quarter(m):
    return f"Q{(m - 1) // 3 + 1}"

def classify_variance(var_pct):
    if var_pct >= 0.05:
        return "Favorable"
    elif var_pct >= 0:
        return "On Track"
    elif var_pct >= -0.15:
        return "Unfavorable"
    else:
        return "Critical"

# ── 1. Revenue Targets ──────────────────────────────────────────────
print("\n  [1/5] Revenue Targets by Channel...")
try:
    df_orders = spark.table("fact.FactOrders")
    monthly = (df_orders
        .withColumn("OrderMonth", trunc(col("OrderDate"), "month"))
        .groupBy("OrderMonth", "Channel")
        .agg(spark_sum("TotalAmount").alias("Revenue"))
        .orderBy("Channel", "OrderMonth")
    ).toPandas()
    monthly["OrderMonth"] = pd.to_datetime(monthly["OrderMonth"])

    last_date = monthly["OrderMonth"].max()
    baseline_start = last_date - pd.DateOffset(months=5)
    baseline = monthly[monthly["OrderMonth"] >= baseline_start]
    channels = monthly["Channel"].unique()
    plan_start = last_date + pd.DateOffset(months=1)
    plan_months = [plan_start + relativedelta(months=i) for i in range(PLANNING_HORIZON)]

    rev_rows = []
    for ch in channels:
        ch_base = baseline[baseline["Channel"] == ch]["Revenue"].values
        if len(ch_base) == 0:
            continue
        pattern = np.tile(ch_base, (PLANNING_HORIZON // len(ch_base)) + 1)[:PLANNING_HORIZON]
        for scenario, growth in SCENARIOS.items():
            monthly_rate = (1 + growth) ** (1/12) - 1
            for i, (pm, base_val) in enumerate(zip(plan_months, pattern)):
                rev_rows.append({
                    "PlanMonth": pm.date(),
                    "Channel": ch,
                    "Scenario": scenario,
                    "TargetRevenue": round(float(base_val * (1 + monthly_rate) ** (i + 1)), 2),
                    "FiscalYear": f"FY{pm.year}",
                    "FiscalQuarter": fiscal_quarter(pm.month),
                    "PlanHorizon": i + 1,
                    "RecordType": "Plan",
                    "ApprovalStatus": "Draft",
                    "LastModifiedBy": "Deploy-Planning.ps1",
                    "LastModifiedAt": GENERATED_AT,
                    "_generated_at": GENERATED_AT,
                })

    schema_rev = StructType([
        StructField("PlanMonth", DateType()),
        StructField("Channel", StringType()),
        StructField("Scenario", StringType()),
        StructField("TargetRevenue", DoubleType()),
        StructField("FiscalYear", StringType()),
        StructField("FiscalQuarter", StringType()),
        StructField("PlanHorizon", IntegerType()),
        StructField("RecordType", StringType()),
        StructField("ApprovalStatus", StringType()),
        StructField("LastModifiedBy", StringType()),
        StructField("LastModifiedAt", TimestampType()),
        StructField("_generated_at", TimestampType()),
    ])
    df_rev = spark.createDataFrame(pd.DataFrame(rev_rows), schema=schema_rev)
    df_rev.write.mode("overwrite").format("delta").option("overwriteSchema", "true").saveAsTable("planning.PlanRevenueTargets")
    print(f"    OK  PlanRevenueTargets: {len(rev_rows)} rows")
except Exception as e:
    print(f"    WARN Revenue targets: {e}")

# ── 2. Financial Targets ────────────────────────────────────────────
print("\n  [2/5] Financial Plan by Account Type...")
try:
    df_budget = spark.table("fact.FactBudget").toPandas()
    last_fy = df_budget["FiscalYear"].max()
    baseline_b = df_budget[df_budget["FiscalYear"] == last_fy]

    # Join AccountType
    df_accts = spark.table("dim.DimAccounts").toPandas()
    baseline_b = baseline_b.merge(df_accts[["AccountID", "AccountType"]], on="AccountID", how="left")
    acct_types = baseline_b["AccountType"].dropna().unique()

    fin_rows = []
    for at in acct_types:
        at_data = baseline_b[baseline_b["AccountType"] == at].sort_values("FiscalMonth")
        monthly_budget = at_data["BudgetAmount"].values
        if len(monthly_budget) == 0:
            continue
        pattern = np.tile(monthly_budget, (PLANNING_HORIZON // len(monthly_budget)) + 1)[:PLANNING_HORIZON]
        for scenario, growth in SCENARIOS.items():
            monthly_rate = (1 + growth) ** (1/12) - 1
            for i, (pm, base_val) in enumerate(zip(plan_months, pattern)):
                fin_rows.append({
                    "PlanMonth": pm.date(),
                    "AccountType": at,
                    "CostCenterID": None,
                    "Scenario": scenario,
                    "PlannedAmount": round(float(base_val * (1 + monthly_rate) ** (i + 1)), 2),
                    "FiscalYear": f"FY{pm.year}",
                    "FiscalQuarter": fiscal_quarter(pm.month),
                    "PlanHorizon": i + 1,
                    "RecordType": "Plan",
                    "ApprovalStatus": "Draft",
                    "LastModifiedBy": "Deploy-Planning.ps1",
                    "LastModifiedAt": GENERATED_AT,
                    "_generated_at": GENERATED_AT,
                })

    schema_fin = StructType([
        StructField("PlanMonth", DateType()),
        StructField("AccountType", StringType()),
        StructField("CostCenterID", StringType()),
        StructField("Scenario", StringType()),
        StructField("PlannedAmount", DoubleType()),
        StructField("FiscalYear", StringType()),
        StructField("FiscalQuarter", StringType()),
        StructField("PlanHorizon", IntegerType()),
        StructField("RecordType", StringType()),
        StructField("ApprovalStatus", StringType()),
        StructField("LastModifiedBy", StringType()),
        StructField("LastModifiedAt", TimestampType()),
        StructField("_generated_at", TimestampType()),
    ])
    df_fin = spark.createDataFrame(pd.DataFrame(fin_rows), schema=schema_fin)
    df_fin.write.mode("overwrite").format("delta").option("overwriteSchema", "true").saveAsTable("planning.PlanFinancialTargets")
    print(f"    OK  PlanFinancialTargets: {len(fin_rows)} rows")
except Exception as e:
    print(f"    WARN Financial targets: {e}")

# ── 3. Workforce Targets ────────────────────────────────────────────
print("\n  [3/5] Workforce Plan by Department...")
try:
    df_payroll = spark.table("fact.FactPayroll").toPandas()
    df_emp = spark.table("dim.DimEmployees").toPandas()
    df_dept = spark.table("dim.DimDepartments").toPandas()

    df_payroll["PayDate"] = pd.to_datetime(df_payroll["PayDate"])
    df_payroll = df_payroll.merge(df_emp[["EmployeeID", "DepartmentID"]], on="EmployeeID", how="left")
    df_payroll = df_payroll.merge(df_dept[["DepartmentID", "DepartmentName"]], on="DepartmentID", how="left")
    df_payroll["PayMonth"] = df_payroll["PayDate"].dt.to_period("M").dt.to_timestamp()

    dept_monthly = (df_payroll.groupby(["PayMonth", "DepartmentName"])
        .agg(Headcount=("EmployeeID", "nunique"), TotalPayroll=("NetPay", "sum"))
        .reset_index())

    departments = dept_monthly["DepartmentName"].dropna().unique()

    wf_rows = []
    for dept in departments:
        dept_data = dept_monthly[dept_monthly["DepartmentName"] == dept].sort_values("PayMonth")
        if dept_data.empty:
            continue
        last_hc = int(dept_data["Headcount"].iloc[-1])
        last_pay = float(dept_data["TotalPayroll"].iloc[-1])

        for scenario, pay_growth in SCENARIOS.items():
            hc_growth = HC_GROWTH[scenario]
            monthly_hc_rate = (1 + hc_growth) ** (1/12) - 1
            monthly_pay_rate = (1 + pay_growth) ** (1/12) - 1
            for i, pm in enumerate(plan_months):
                wf_rows.append({
                    "PlanMonth": pm.date(),
                    "Department": dept,
                    "Scenario": scenario,
                    "PlannedHeadcount": max(1, round(last_hc * (1 + monthly_hc_rate) ** (i + 1))),
                    "PlannedPayroll": round(last_pay * (1 + monthly_pay_rate) ** (i + 1), 2),
                    "FiscalYear": f"FY{pm.year}",
                    "FiscalQuarter": fiscal_quarter(pm.month),
                    "PlanHorizon": i + 1,
                    "RecordType": "Plan",
                    "ApprovalStatus": "Draft",
                    "LastModifiedBy": "Deploy-Planning.ps1",
                    "LastModifiedAt": GENERATED_AT,
                    "_generated_at": GENERATED_AT,
                })

    schema_wf = StructType([
        StructField("PlanMonth", DateType()),
        StructField("Department", StringType()),
        StructField("Scenario", StringType()),
        StructField("PlannedHeadcount", IntegerType()),
        StructField("PlannedPayroll", DoubleType()),
        StructField("FiscalYear", StringType()),
        StructField("FiscalQuarter", StringType()),
        StructField("PlanHorizon", IntegerType()),
        StructField("RecordType", StringType()),
        StructField("ApprovalStatus", StringType()),
        StructField("LastModifiedBy", StringType()),
        StructField("LastModifiedAt", TimestampType()),
        StructField("_generated_at", TimestampType()),
    ])
    df_wf = spark.createDataFrame(pd.DataFrame(wf_rows), schema=schema_wf)
    df_wf.write.mode("overwrite").format("delta").option("overwriteSchema", "true").saveAsTable("planning.PlanWorkforceTargets")
    print(f"    OK  PlanWorkforceTargets: {len(wf_rows)} rows")
except Exception as e:
    print(f"    WARN Workforce targets: {e}")

# ── 4. Plan vs Actual Variance ──────────────────────────────────────
print("\n  [4/5] Plan vs Actual Variance Analysis...")
try:
    df_budget_var = spark.table("fact.FactBudget").toPandas()
    df_accts_var = spark.table("dim.DimAccounts").toPandas()
    df_budget_var = df_budget_var.merge(df_accts_var[["AccountID", "AccountType", "AccountName"]], on="AccountID", how="left")

    var_rows = []
    for _, row in df_budget_var.iterrows():
        var_pct = row.get("VariancePct", 0)
        if pd.isna(var_pct):
            var_pct = 0
        var_pct = var_pct / 100

        is_revenue = str(row.get("AccountType", "")).lower() == "revenue"
        domain = "Revenue" if is_revenue else "Finance"
        adjusted = var_pct if is_revenue else -var_pct

        var_rows.append({
            "Domain": domain,
            "Category": row.get("AccountName", row.get("AccountType", "Unknown")),
            "FiscalYear": row["FiscalYear"],
            "FiscalQuarter": row.get("FiscalQuarter", ""),
            "FiscalMonth": int(row.get("FiscalMonth", 0)),
            "PlannedAmount": float(row.get("BudgetAmount", 0)),
            "ActualAmount": float(row.get("ActualAmount", 0)),
            "Variance": float(row.get("Variance", 0)),
            "VariancePct": var_pct,
            "Status": classify_variance(adjusted),
            "_generated_at": GENERATED_AT,
        })

    schema_var = StructType([
        StructField("Domain", StringType()),
        StructField("Category", StringType()),
        StructField("FiscalYear", StringType()),
        StructField("FiscalQuarter", StringType()),
        StructField("FiscalMonth", IntegerType()),
        StructField("PlannedAmount", DoubleType()),
        StructField("ActualAmount", DoubleType()),
        StructField("Variance", DoubleType()),
        StructField("VariancePct", DoubleType()),
        StructField("Status", StringType()),
        StructField("_generated_at", TimestampType()),
    ])
    df_var = spark.createDataFrame(pd.DataFrame(var_rows), schema=schema_var)
    df_var.write.mode("overwrite").format("delta").option("overwriteSchema", "true").saveAsTable("planning.PlanVarianceAnalysis")
    print(f"    OK  PlanVarianceAnalysis: {len(var_rows)} rows")
except Exception as e:
    print(f"    WARN Variance analysis: {e}")

# ── 5. Scenario Comparison Summary ──────────────────────────────────
print("\n  [5/5] Scenario Comparison Summary...")
try:
    summary_rows = []

    # Revenue
    try:
        df_r = spark.table("planning.PlanRevenueTargets").toPandas()
        for (scenario, fq), grp in df_r.groupby(["Scenario", "FiscalQuarter"]):
            summary_rows.append({
                "Domain": "Revenue",
                "Scenario": scenario,
                "FiscalQuarter": fq,
                "PlannedTotal": round(float(grp["TargetRevenue"].sum()), 2),
                "RecordType": "ScenarioSummary",
                "_generated_at": GENERATED_AT,
            })
    except Exception:
        pass

    # Finance
    try:
        df_f = spark.table("planning.PlanFinancialTargets").toPandas()
        for (scenario, fq), grp in df_f.groupby(["Scenario", "FiscalQuarter"]):
            summary_rows.append({
                "Domain": "Finance",
                "Scenario": scenario,
                "FiscalQuarter": fq,
                "PlannedTotal": round(float(grp["PlannedAmount"].sum()), 2),
                "RecordType": "ScenarioSummary",
                "_generated_at": GENERATED_AT,
            })
    except Exception:
        pass

    # Workforce
    try:
        df_w = spark.table("planning.PlanWorkforceTargets").toPandas()
        for (scenario, fq), grp in df_w.groupby(["Scenario", "FiscalQuarter"]):
            summary_rows.append({
                "Domain": "Workforce",
                "Scenario": scenario,
                "FiscalQuarter": fq,
                "PlannedTotal": round(float(grp["PlannedPayroll"].sum()), 2),
                "RecordType": "ScenarioSummary",
                "_generated_at": GENERATED_AT,
            })
    except Exception:
        pass

    schema_sum = StructType([
        StructField("Domain", StringType()),
        StructField("Scenario", StringType()),
        StructField("FiscalQuarter", StringType()),
        StructField("PlannedTotal", DoubleType()),
        StructField("RecordType", StringType()),
        StructField("_generated_at", TimestampType()),
    ])
    df_sum = spark.createDataFrame(pd.DataFrame(summary_rows), schema=schema_sum)
    df_sum.write.mode("overwrite").format("delta").option("overwriteSchema", "true").saveAsTable("planning.PlanScenarioSummary")
    print(f"    OK  PlanScenarioSummary: {len(summary_rows)} rows")
except Exception as e:
    print(f"    WARN Scenario summary: {e}")

# ── Final Summary ────────────────────────────────────────────────────
print()
print("=" * 60)
print("  Planning in Fabric IQ - Population Complete")
print("=" * 60)
tables = ["PlanRevenueTargets", "PlanFinancialTargets", "PlanWorkforceTargets",
          "PlanVarianceAnalysis", "PlanScenarioSummary"]
for t in tables:
    try:
        cnt = spark.table(f"planning.{t}").count()
        print(f"  planning.{t}: {cnt} rows")
    except Exception:
        print(f"  planning.{t}: NOT FOUND")

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }
