table 'Budget'
	lineageTag: 20000002-0001-0001-0001-000000000001

	measure 'Budget Amount' = SUM('Budget'[Budgeted Amount])
		formatString: $#,0;($#,0)
		displayFolder: Finance \ Budget
		lineageTag: 20000002-0001-0001-0001-100000000001

	measure 'Actual Amount' = SUM('Budget'[Actual Spent])
		formatString: $#,0;($#,0)
		displayFolder: Finance \ Budget
		lineageTag: 20000002-0001-0001-0001-100000000002

	measure 'Budget Variance' = SUM('Budget'[Variance])
		formatString: $#,0;($#,0)
		displayFolder: Finance \ Budget
		lineageTag: 20000002-0001-0001-0001-100000000003

	measure 'Budget Variance %' = DIVIDE([Budget Variance],ABS([Budget Amount]),0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Finance \ Budget
		lineageTag: 20000002-0001-0001-0001-100000000004

	measure 'Budget Attainment' = DIVIDE([Actual Amount],[Budget Amount],0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Finance \ Budget
		lineageTag: 20000002-0001-0001-0001-100000000005

	column 'Budget ID'
		dataType: string
		summarizeBy: none
		sourceColumn: BudgetID
		lineageTag: 20000002-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		summarizeBy: none
		sourceColumn: FiscalYear
		lineageTag: 20000002-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		summarizeBy: none
		sourceColumn: FiscalQuarter
		lineageTag: 20000002-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		summarizeBy: none
		sourceColumn: FiscalMonth
		lineageTag: 20000002-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Account ID'
		dataType: int64
		summarizeBy: none
		sourceColumn: AccountID
		lineageTag: 20000002-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Cost Center ID'
		dataType: string
		summarizeBy: none
		sourceColumn: CostCenterID
		lineageTag: 20000002-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Budgeted Amount'
		dataType: double
		summarizeBy: sum
		sourceColumn: BudgetAmount
		lineageTag: 20000002-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Actual Spent'
		dataType: double
		summarizeBy: sum
		sourceColumn: ActualAmount
		lineageTag: 20000002-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column Variance
		dataType: double
		summarizeBy: sum
		sourceColumn: Variance
		lineageTag: 20000002-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column 'Variance %'
		dataType: double
		summarizeBy: sum
		sourceColumn: VariancePct
		lineageTag: 20000002-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition 'Budget' = entity
		mode: directLake
		schemaName: fact
		entityName: factbudget
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
