table 'Employees'
	lineageTag: 10000008-0001-0001-0001-000000000001

	measure 'Total Headcount' = CALCULATE(COUNTROWS('Employees'),'Employees'[Is Active] = TRUE())
		formatString: #,0
		displayFolder: HR \ Workforce
		lineageTag: 10000008-0001-0001-0001-100000000001

	measure 'Full Time Employees' = CALCULATE(COUNTROWS('Employees'),'Employees'[Is Active] = TRUE(),'Employees'[Employment Type] = "Full-Time")
		formatString: #,0
		displayFolder: HR \ Workforce
		lineageTag: 10000008-0001-0001-0001-100000000002

	measure 'Part Time & Contract' = CALCULATE(COUNTROWS('Employees'),'Employees'[Is Active] = TRUE(),'Employees'[Employment Type] IN {"Part-Time", "Contract"})
		formatString: #,0
		displayFolder: HR \ Workforce
		lineageTag: 10000008-0001-0001-0001-100000000003

	measure 'Avg Tenure Years' = AVERAGEX(FILTER('Employees', 'Employees'[Is Active] = TRUE()),DATEDIFF('Employees'[Hire Date], TODAY(), YEAR))
		formatString: 0.0
		displayFolder: HR \ Workforce
		lineageTag: 10000008-0001-0001-0001-100000000004

	measure 'Revenue per Employee' = DIVIDE([Total Revenue], [Total Headcount], 0)
		formatString: $#,0.00
		displayFolder: HR \ Workforce
		lineageTag: 10000008-0001-0001-0001-100000000005

	column 'Employee ID'
		dataType: string
		summarizeBy: none
		sourceColumn: EmployeeID
		lineageTag: 10000008-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		summarizeBy: none
		sourceColumn: FirstName
		lineageTag: 10000008-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		summarizeBy: none
		sourceColumn: LastName
		lineageTag: 10000008-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		summarizeBy: none
		sourceColumn: Email
		lineageTag: 10000008-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Hire Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: HireDate
		lineageTag: 10000008-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Department ID'
		dataType: string
		summarizeBy: none
		sourceColumn: DepartmentID
		lineageTag: 10000008-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		summarizeBy: none
		sourceColumn: JobTitle
		lineageTag: 10000008-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Manager ID'
		dataType: string
		summarizeBy: none
		sourceColumn: ManagerID
		lineageTag: 10000008-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Employment Type'
		dataType: string
		summarizeBy: none
		sourceColumn: EmploymentType
		lineageTag: 10000008-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		summarizeBy: none
		sourceColumn: Location
		lineageTag: 10000008-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column 'Geo ID'
		dataType: string
		summarizeBy: none
		sourceColumn: GeoID
		lineageTag: 10000008-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	column 'Is Active'
		dataType: boolean
		summarizeBy: none
		sourceColumn: IsActive
		lineageTag: 10000008-0001-0001-0001-200000000012

		annotation SummarizationSetBy = Automatic

	partition 'Employees' = entity
		mode: directLake
		schemaName: dim
		entityName: dimemployees
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
