table FactOrders
	lineageTag: 20000003-0001-0001-0001-000000000001

	measure 'Total Orders' = DISTINCTCOUNT(FactOrders[OrderID])
		formatString: #,0
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000001

	measure 'Total Units Sold' = SUM(FactOrders[Quantity])
		formatString: #,0
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000002

	measure 'Order Revenue' = SUM(FactOrders[TotalAmount])
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000003

	measure 'Average Order Value' = DIVIDE([Order Revenue], [Total Orders], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000004

	measure 'Average Discount' = AVERAGE(FactOrders[Discount])
		formatString: 0.0%
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000005

	measure 'Average Selling Price' = DIVIDE([Order Revenue], [Total Units Sold], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000006

	measure 'Online Revenue' = CALCULATE([Order Revenue], FactOrders[Channel] = "Online")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000007

	measure 'Retail Revenue' = CALCULATE([Order Revenue], FactOrders[Channel] = "Retail")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000008

	measure 'Digital Revenue' = CALCULATE([Order Revenue], FactOrders[Channel] = "Digital")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000009

	measure 'International Revenue' = CALCULATE([Order Revenue], FactOrders[Channel] = "International")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000010

	measure 'Online Revenue Share' = DIVIDE([Online Revenue], [Order Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000011

	measure 'Active Customers' = DISTINCTCOUNT(FactOrders[CustomerID])
		formatString: #,0
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000012

	measure 'New Customers' =
		CALCULATE(
			DISTINCTCOUNT(FactOrders[CustomerID]),
			FILTER(
				VALUES(FactOrders[CustomerID]),
				CALCULATE(MIN(FactOrders[OrderDate])) >= MIN(DimDate[FullDate])
			)
		)
		formatString: #,0
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000013

	measure 'Revenue per Customer' = DIVIDE([Order Revenue], [Active Customers], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000014

	measure 'Avg Ship Days' = AVERAGE(DATEDIFF(FactOrders[OrderDate], FactOrders[ShipDate], DAY))
		formatString: 0.0
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000015

	measure 'Avg Delivery Days' = AVERAGE(DATEDIFF(FactOrders[OrderDate], FactOrders[DeliveryDate], DAY))
		formatString: 0.0
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000016

	measure 'On Time Delivery Rate' =
		DIVIDE(
			CALCULATE(
				COUNTROWS(FactOrders),
				DATEDIFF(FactOrders[OrderDate], FactOrders[DeliveryDate], DAY) <= 7
			),
			COUNTROWS(FactOrders),
			0
		)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000017

	measure 'International Customer Count' = CALCULATE(DISTINCTCOUNT(DimCustomers[CustomerID]),DimGeography[Country] <> "United States")
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000018

	measure 'Domestic Customer Count' = CALCULATE(DISTINCTCOUNT(DimCustomers[CustomerID]),DimGeography[Country] = "United States")
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000019

	measure 'Intl Revenue' = CALCULATE(SUM(FactOrders[TotalAmount]),DimGeography[Country] <> "United States")
		formatString: $#,0;($#,0)
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000020

	measure 'Domestic Revenue' = CALCULATE(SUM(FactOrders[TotalAmount]),DimGeography[Country] = "United States")
		formatString: $#,0;($#,0)
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000021

	measure 'International Revenue %' = DIVIDE([Intl Revenue], [Order Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000022

	measure 'Countries Served' = DISTINCTCOUNT(DimGeography[Country])
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000023

	measure 'Continents Served' = DISTINCTCOUNT(DimGeography[Continent])
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000024

	measure 'Revenue per Country' = DIVIDE([Order Revenue],[Countries Served],0)
		formatString: $#,0.00
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000025

	measure 'Employee Locations' = CALCULATE(DISTINCTCOUNT(DimGeography[City]),USERELATIONSHIP(DimEmployees[GeoID],DimGeography[GeoID]),VALUES(DimEmployees[EmployeeID]))
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000026

	column OrderID
		dataType: string
		summarizeBy: none
		sourceColumn: OrderID
		lineageTag: 20000003-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		summarizeBy: none
		sourceColumn: OrderDate
		lineageTag: 20000003-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerID
		lineageTag: 20000003-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column BookID
		dataType: string
		summarizeBy: none
		sourceColumn: BookID
		lineageTag: 20000003-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 20000003-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitPrice
		lineageTag: 20000003-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 20000003-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column TotalAmount
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalAmount
		lineageTag: 20000003-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column OrderStatus
		dataType: string
		summarizeBy: none
		sourceColumn: OrderStatus
		lineageTag: 20000003-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ShipDate
		lineageTag: 20000003-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column DeliveryDate
		dataType: dateTime
		summarizeBy: none
		sourceColumn: DeliveryDate
		lineageTag: 20000003-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	column WarehouseID
		dataType: string
		summarizeBy: none
		sourceColumn: WarehouseID
		lineageTag: 20000003-0001-0001-0001-200000000012

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: string
		summarizeBy: none
		sourceColumn: SalesRepID
		lineageTag: 20000003-0001-0001-0001-200000000013

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel
		lineageTag: 20000003-0001-0001-0001-200000000014

		annotation SummarizationSetBy = Automatic

	partition FactOrders = entity
		mode: directLake
		schemaName: fact
		entityName: FactOrders
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
