table 'Forecast Financial'
	lineageTag: 30000003-0001-0001-0001-000000000001

	measure 'Forecast P&L Amount' = IF(HASONEVALUE('Forecast Financial'[Record Type]), SUM('Forecast Financial'[Amount]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Financial
		lineageTag: 30000003-0001-0001-0001-100000000001

	measure 'Forecast P&L Lower' = IF(HASONEVALUE('Forecast Financial'[Record Type]), SUM('Forecast Financial'[Lower Bound]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Financial
		lineageTag: 30000003-0001-0001-0001-100000000002

	measure 'Forecast P&L Upper' = IF(HASONEVALUE('Forecast Financial'[Record Type]), SUM('Forecast Financial'[Upper Bound]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Financial
		lineageTag: 30000003-0001-0001-0001-100000000003

	column 'Forecast Month'
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: ForecastMonth
		lineageTag: 30000003-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'P&L Category'
		dataType: string
		summarizeBy: none
		sourceColumn: PLCategory
		lineageTag: 30000003-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		summarizeBy: sum
		sourceColumn: Amount
		lineageTag: 30000003-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column 'Transaction Count'
		dataType: int64
		summarizeBy: sum
		sourceColumn: TransactionCount
		lineageTag: 30000003-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Lower Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: LowerBound
		lineageTag: 30000003-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Upper Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: UpperBound
		lineageTag: 30000003-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Forecast Horizon'
		dataType: int64
		summarizeBy: none
		sourceColumn: ForecastHorizon
		lineageTag: 30000003-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Record Type'
		dataType: string
		summarizeBy: none
		sourceColumn: RecordType
		lineageTag: 30000003-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Forecast Model'
		dataType: string
		summarizeBy: none
		sourceColumn: ForecastModel
		lineageTag: 30000003-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	partition 'Forecast Financial' = entity
		mode: directLake
		schemaName: analytics
		entityName: forecastfinancial
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
