table 'Forecast Sales Revenue'
	lineageTag: 30000001-0001-0001-0001-000000000001

	measure 'Forecast Revenue' = IF(HASONEVALUE('Forecast Sales Revenue'[Record Type]), SUM('Forecast Sales Revenue'[Revenue]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Sales
		lineageTag: 30000001-0001-0001-0001-100000000001

	measure 'Revenue Lower Bound' = IF(HASONEVALUE('Forecast Sales Revenue'[Record Type]), SUM('Forecast Sales Revenue'[Lower Bound]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Sales
		lineageTag: 30000001-0001-0001-0001-100000000002

	measure 'Revenue Upper Bound' = IF(HASONEVALUE('Forecast Sales Revenue'[Record Type]), SUM('Forecast Sales Revenue'[Upper Bound]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Sales
		lineageTag: 30000001-0001-0001-0001-100000000003

	measure 'Forecast vs Actual Revenue' =
		VAR _forecast = CALCULATE(SUM('Forecast Sales Revenue'[Revenue]), 'Forecast Sales Revenue'[Record Type] = "Forecast")
		VAR _actual = CALCULATE(SUM('Forecast Sales Revenue'[Revenue]), 'Forecast Sales Revenue'[Record Type] = "Actual")
		RETURN IF(_actual <> 0, DIVIDE(_forecast - _actual, _actual, 0), BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecasting \ Sales
		lineageTag: 30000001-0001-0001-0001-100000000004

	column 'Forecast Month'
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: ForecastMonth
		lineageTag: 30000001-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel
		lineageTag: 30000001-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: Revenue
		lineageTag: 30000001-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: Orders
		lineageTag: 30000001-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: Customers
		lineageTag: 30000001-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Lower Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: LowerBound
		lineageTag: 30000001-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Upper Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: UpperBound
		lineageTag: 30000001-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Forecast Horizon'
		dataType: int64
		summarizeBy: none
		sourceColumn: ForecastHorizon
		lineageTag: 30000001-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Record Type'
		dataType: string
		summarizeBy: none
		sourceColumn: RecordType
		lineageTag: 30000001-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column 'Forecast Model'
		dataType: string
		summarizeBy: none
		sourceColumn: ForecastModel
		lineageTag: 30000001-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	partition 'Forecast Sales Revenue' = entity
		mode: directLake
		schemaName: analytics
		entityName: forecastsalesrevenue
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
