table 'Forecast Inventory Demand'
	lineageTag: 30000004-0001-0001-0001-000000000001

	measure 'Forecast Demand Units' = SUM('Forecast Inventory Demand'[Units Demanded])
		formatString: #,0
		displayFolder: Forecasting \ Inventory
		lineageTag: 30000004-0001-0001-0001-100000000001

	measure 'Stock Coverage Months' = CALCULATE(AVERAGE('Forecast Inventory Demand'[Stock Cover Months]), 'Forecast Inventory Demand'[Record Type] = "Forecast", 'Forecast Inventory Demand'[Forecast Horizon] = 1)
		formatString: 0.0
		displayFolder: Forecasting \ Inventory
		lineageTag: 30000004-0001-0001-0001-100000000002

	measure 'Cumulative Forecast Demand' = SUM('Forecast Inventory Demand'[Cumulative Demand])
		formatString: #,0
		displayFolder: Forecasting \ Inventory
		lineageTag: 30000004-0001-0001-0001-100000000003

	column 'Forecast Month'
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: ForecastMonth
		lineageTag: 30000004-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'Warehouse ID'
		dataType: string
		summarizeBy: none
		sourceColumn: WarehouseID
		lineageTag: 30000004-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Units Demanded'
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitsDemanded
		lineageTag: 30000004-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: Revenue
		lineageTag: 30000004-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Lower Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: LowerBound
		lineageTag: 30000004-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Upper Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: UpperBound
		lineageTag: 30000004-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Forecast Horizon'
		dataType: int64
		summarizeBy: none
		sourceColumn: ForecastHorizon
		lineageTag: 30000004-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Record Type'
		dataType: string
		summarizeBy: none
		sourceColumn: RecordType
		lineageTag: 30000004-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Forecast Model'
		dataType: string
		summarizeBy: none
		sourceColumn: ForecastModel
		lineageTag: 30000004-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column 'Current Stock'
		dataType: double
		summarizeBy: sum
		sourceColumn: CurrentStock
		lineageTag: 30000004-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column 'Cumulative Demand'
		dataType: double
		summarizeBy: sum
		sourceColumn: CumulativeDemand
		lineageTag: 30000004-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	column 'Stock Cover Months'
		dataType: double
		summarizeBy: average
		sourceColumn: StockCoverMonths
		lineageTag: 30000004-0001-0001-0001-200000000012

		annotation SummarizationSetBy = Automatic

	partition 'Forecast Inventory Demand' = entity
		mode: directLake
		schemaName: analytics
		entityName: forecastinventorydemand
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
