table 'Forecast Genre Demand'
	lineageTag: 30000002-0001-0001-0001-000000000001

	measure 'Forecast Unit Demand' = SUM('Forecast Genre Demand'[Unit Demand])
		formatString: #,0
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000001

	measure 'Forecast Genre Revenue' = SUM('Forecast Genre Demand'[Revenue])
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000002

	measure 'Demand Confidence Range' =
		VAR _lower = SUM('Forecast Genre Demand'[Lower Bound])
		VAR _upper = SUM('Forecast Genre Demand'[Upper Bound])
		RETURN _upper - _lower
		formatString: #,0
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000003

	column 'Forecast Month'
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: ForecastMonth
		lineageTag: 30000002-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		summarizeBy: none
		sourceColumn: Genre
		lineageTag: 30000002-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Unit Demand'
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitDemand
		lineageTag: 30000002-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: Revenue
		lineageTag: 30000002-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Lower Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: LowerBound
		lineageTag: 30000002-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Upper Bound'
		dataType: double
		summarizeBy: sum
		sourceColumn: UpperBound
		lineageTag: 30000002-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Forecast Horizon'
		dataType: int64
		summarizeBy: none
		sourceColumn: ForecastHorizon
		lineageTag: 30000002-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Record Type'
		dataType: string
		summarizeBy: none
		sourceColumn: RecordType
		lineageTag: 30000002-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Forecast Model'
		dataType: string
		summarizeBy: none
		sourceColumn: ForecastModel
		lineageTag: 30000002-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	partition 'Forecast Genre Demand' = entity
		mode: directLake
		schemaName: analytics
		entityName: forecastgenredemand
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
