table ForecastGenreDemand
	lineageTag: 30000002-0001-0001-0001-000000000001

	measure 'Forecast Unit Demand' = IF(HASONEVALUE(ForecastGenreDemand[RecordType]), SUM(ForecastGenreDemand[UnitDemand]), BLANK())
		formatString: #,0
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000001

	measure 'Forecast Genre Revenue' = IF(HASONEVALUE(ForecastGenreDemand[RecordType]), SUM(ForecastGenreDemand[Revenue]), BLANK())
		formatString: $#,0;($#,0)
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000002

	measure 'Demand Confidence Range' =
		VAR _lower = SUM(ForecastGenreDemand[LowerBound])
		VAR _upper = SUM(ForecastGenreDemand[UpperBound])
		RETURN _upper - _lower
		formatString: #,0
		displayFolder: Forecasting \ Genre
		lineageTag: 30000002-0001-0001-0001-100000000003

	column ForecastMonth
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: ForecastMonth
		lineageTag: 30000002-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		summarizeBy: none
		sourceColumn: Genre
		lineageTag: 30000002-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column UnitDemand
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitDemand
		lineageTag: 30000002-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: Revenue
		lineageTag: 30000002-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column LowerBound
		dataType: double
		summarizeBy: sum
		sourceColumn: LowerBound
		lineageTag: 30000002-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column UpperBound
		dataType: double
		summarizeBy: sum
		sourceColumn: UpperBound
		lineageTag: 30000002-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column ForecastHorizon
		dataType: int64
		summarizeBy: none
		sourceColumn: ForecastHorizon
		lineageTag: 30000002-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column RecordType
		dataType: string
		summarizeBy: none
		sourceColumn: RecordType
		lineageTag: 30000002-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column ForecastModel
		dataType: string
		summarizeBy: none
		sourceColumn: ForecastModel
		lineageTag: 30000002-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	partition ForecastGenreDemand = entity
		mode: directLake
		schemaName: analytics
		entityName: ForecastGenreDemand
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
