table 'Orders'
	lineageTag: 20000003-0001-0001-0001-000000000001

	measure 'Total Orders' = DISTINCTCOUNT('Orders'[Order ID])
		formatString: #,0
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000001

	measure 'Total Units Sold' = SUM('Orders'[Quantity])
		formatString: #,0
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000002

	measure 'Order Revenue' = SUM('Orders'[Total Amount])
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000003

	measure 'Average Order Value' = DIVIDE([Order Revenue], [Total Orders], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000004

	measure 'Average Discount' = AVERAGE('Orders'[Discount])
		formatString: 0.0%
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000005

	measure 'Average Selling Price' = DIVIDE([Order Revenue], [Total Units Sold], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Orders
		lineageTag: 20000003-0001-0001-0001-100000000006

	measure 'Online Revenue' = CALCULATE([Order Revenue], 'Orders'[Channel] = "Online")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000007

	measure 'Retail Revenue' = CALCULATE([Order Revenue], 'Orders'[Channel] = "Retail")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000008

	measure 'Digital Revenue' = CALCULATE([Order Revenue], 'Orders'[Channel] = "Digital")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000009

	measure 'International Revenue' = CALCULATE([Order Revenue], 'Orders'[Channel] = "International")
		formatString: $#,0;($#,0)
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000010

	measure 'Online Revenue Share' = DIVIDE([Online Revenue], [Order Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations \ Channels
		lineageTag: 20000003-0001-0001-0001-100000000011

	measure 'Active Customers' = DISTINCTCOUNT('Orders'[Customer ID])
		formatString: #,0
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000012

	measure 'New Customers' =
		CALCULATE(
			DISTINCTCOUNT('Orders'[Customer ID]),
			FILTER(
				VALUES('Orders'[Customer ID]),
				CALCULATE(MIN('Orders'[Order Date])) >= MIN('Date'[Full Date])
			)
		)
		formatString: #,0
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000013

	measure 'Revenue per Customer' = DIVIDE([Order Revenue], [Active Customers], 0)
		formatString: $#,0.00
		displayFolder: Operations \ Customers
		lineageTag: 20000003-0001-0001-0001-100000000014

	measure 'Avg Ship Days' = AVERAGEX('Orders', DATEDIFF('Orders'[Order Date], 'Orders'[Ship Date], DAY))
		formatString: 0.0
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000015

	measure 'Avg Delivery Days' = AVERAGEX('Orders', DATEDIFF('Orders'[Order Date], 'Orders'[Delivery Date], DAY))
		formatString: 0.0
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000016

	measure 'On Time Delivery Rate' =
		DIVIDE(
			CALCULATE(
				COUNTROWS('Orders'),
				DATEDIFF('Orders'[Order Date], 'Orders'[Delivery Date], DAY) <= 7
			),
			COUNTROWS('Orders'),
			0
		)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations \ Fulfillment
		lineageTag: 20000003-0001-0001-0001-100000000017

	measure 'International Customer Count' = CALCULATE(DISTINCTCOUNT('Customers'[Customer ID]),'Geography'[Country] <> "United States")
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000018

	measure 'Domestic Customer Count' = CALCULATE(DISTINCTCOUNT('Customers'[Customer ID]),'Geography'[Country] = "United States")
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000019

	measure 'Intl Revenue' = CALCULATE(SUM('Orders'[Total Amount]),'Geography'[Country] <> "United States")
		formatString: $#,0;($#,0)
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000020

	measure 'Domestic Revenue' = CALCULATE(SUM('Orders'[Total Amount]),'Geography'[Country] = "United States")
		formatString: $#,0;($#,0)
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000021

	measure 'International Revenue %' = DIVIDE([Intl Revenue], [Order Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000022

	measure 'Countries Served' = DISTINCTCOUNT('Geography'[Country])
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000023

	measure 'Continents Served' = DISTINCTCOUNT('Geography'[Continent])
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000024

	measure 'Revenue per Country' = DIVIDE([Order Revenue],[Countries Served],0)
		formatString: $#,0.00
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000025

	measure 'Employee Locations' = CALCULATE(DISTINCTCOUNT('Geography'[City]),USERELATIONSHIP('Employees'[Geo ID],'Geography'[Geo ID]),VALUES('Employees'[Employee ID]))
		formatString: #,0
		displayFolder: Geographic
		lineageTag: 20000003-0001-0001-0001-100000000026

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: OrderID
		lineageTag: 20000003-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: OrderDate
		lineageTag: 20000003-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerID
		lineageTag: 20000003-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column 'Book ID'
		dataType: string
		summarizeBy: none
		sourceColumn: BookID
		lineageTag: 20000003-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 20000003-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitPrice
		lineageTag: 20000003-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 20000003-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalAmount
		lineageTag: 20000003-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		summarizeBy: none
		sourceColumn: OrderStatus
		lineageTag: 20000003-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ShipDate
		lineageTag: 20000003-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column 'Delivery Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: DeliveryDate
		lineageTag: 20000003-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	column 'Warehouse ID'
		dataType: string
		summarizeBy: none
		sourceColumn: WarehouseID
		lineageTag: 20000003-0001-0001-0001-200000000012

		annotation SummarizationSetBy = Automatic

	column 'Sales Rep ID'
		dataType: string
		summarizeBy: none
		sourceColumn: SalesRepID
		lineageTag: 20000003-0001-0001-0001-200000000013

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel
		lineageTag: 20000003-0001-0001-0001-200000000014

		annotation SummarizationSetBy = Automatic

	partition 'Orders' = entity
		mode: directLake
		schemaName: fact
		entityName: factorders
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
