table 'Performance Reviews'
	lineageTag: 20000007-0001-0001-0001-000000000001

	measure 'Avg Performance Score' = AVERAGE('Performance Reviews'[Overall Score])
		formatString: 0.0
		displayFolder: HR \ Performance
		lineageTag: 20000007-0001-0001-0001-100000000001

	measure 'Top Performers' = CALCULATE(COUNTROWS('Performance Reviews'),'Performance Reviews'[Performance Rating] IN {"Exceeds Expectations", "Outstanding"})
		formatString: #,0
		displayFolder: HR \ Performance
		lineageTag: 20000007-0001-0001-0001-100000000002

	measure 'Top Performer Rate' = DIVIDE([Top Performers],COUNTROWS('Performance Reviews'),0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: HR \ Performance
		lineageTag: 20000007-0001-0001-0001-100000000003

	column 'Review ID'
		dataType: string
		summarizeBy: none
		sourceColumn: ReviewID
		lineageTag: 20000007-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'Employee ID'
		dataType: string
		summarizeBy: none
		sourceColumn: EmployeeID
		lineageTag: 20000007-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Review Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: ReviewDate
		lineageTag: 20000007-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column 'Reviewer ID'
		dataType: string
		summarizeBy: none
		sourceColumn: ReviewerID
		lineageTag: 20000007-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Performance Rating'
		dataType: string
		summarizeBy: none
		sourceColumn: PerformanceRating
		lineageTag: 20000007-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column 'Goals Met'
		dataType: string
		summarizeBy: none
		sourceColumn: GoalsMet
		lineageTag: 20000007-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column Strengths
		dataType: string
		summarizeBy: none
		sourceColumn: Strengths
		lineageTag: 20000007-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column 'Areas for Improvement'
		dataType: string
		summarizeBy: none
		sourceColumn: AreasForImprovement
		lineageTag: 20000007-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Overall Score'
		dataType: double
		summarizeBy: sum
		sourceColumn: OverallScore
		lineageTag: 20000007-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	partition 'Performance Reviews' = entity
		mode: directLake
		schemaName: fact
		entityName: factperformancereviews
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
