table 'Recruitment'
	lineageTag: 20000008-0001-0001-0001-000000000001

	measure 'Open Positions' = CALCULATE(COUNTROWS('Recruitment'),'Recruitment'[Status] = "Open")
		formatString: #,0
		displayFolder: HR \ Recruitment
		lineageTag: 20000008-0001-0001-0001-100000000001

	measure 'Avg Time to Fill' = CALCULATE(AVERAGE('Recruitment'[Time to Fill Days]),'Recruitment'[Status] = "Filled")
		formatString: 0.0
		displayFolder: HR \ Recruitment
		lineageTag: 20000008-0001-0001-0001-100000000002

	measure 'Offer Acceptance Rate' = DIVIDE(SUM('Recruitment'[Offer Accepted]),SUM('Recruitment'[Offers Extended]),0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: HR \ Recruitment
		lineageTag: 20000008-0001-0001-0001-100000000003

	measure 'Application to Interview Rate' = DIVIDE(SUM('Recruitment'[Interviewed]),SUM('Recruitment'[Applications Received]),0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: HR \ Recruitment
		lineageTag: 20000008-0001-0001-0001-100000000004

	measure 'Cost per Hire' = DIVIDE(CALCULATE(ABS(SUM('Financial Transactions'[Amount])), 'Accounts'[Account ID] = 1050),CALCULATE(COUNTROWS('Recruitment'), 'Recruitment'[Status] = "Filled"),0)
		formatString: $#,0.00
		displayFolder: HR \ Recruitment
		lineageTag: 20000008-0001-0001-0001-100000000005

	column 'Requisition ID'
		dataType: string
		summarizeBy: none
		sourceColumn: RequisitionID
		lineageTag: 20000008-0001-0001-0001-200000000001

		annotation SummarizationSetBy = Automatic

	column 'Department ID'
		dataType: string
		summarizeBy: none
		sourceColumn: DepartmentID
		lineageTag: 20000008-0001-0001-0001-200000000002

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		summarizeBy: none
		sourceColumn: JobTitle
		lineageTag: 20000008-0001-0001-0001-200000000003

		annotation SummarizationSetBy = Automatic

	column 'Open Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: OpenDate
		lineageTag: 20000008-0001-0001-0001-200000000004

		annotation SummarizationSetBy = Automatic

	column 'Close Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: CloseDate
		lineageTag: 20000008-0001-0001-0001-200000000005

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status
		lineageTag: 20000008-0001-0001-0001-200000000006

		annotation SummarizationSetBy = Automatic

	column 'Applications Received'
		dataType: int64
		summarizeBy: sum
		sourceColumn: ApplicationsReceived
		lineageTag: 20000008-0001-0001-0001-200000000007

		annotation SummarizationSetBy = Automatic

	column Interviewed
		dataType: int64
		summarizeBy: sum
		sourceColumn: Interviewed
		lineageTag: 20000008-0001-0001-0001-200000000008

		annotation SummarizationSetBy = Automatic

	column 'Offers Extended'
		dataType: int64
		summarizeBy: sum
		sourceColumn: OffersExtended
		lineageTag: 20000008-0001-0001-0001-200000000009

		annotation SummarizationSetBy = Automatic

	column 'Offer Accepted'
		dataType: int64
		summarizeBy: sum
		sourceColumn: OfferAccepted
		lineageTag: 20000008-0001-0001-0001-200000000010

		annotation SummarizationSetBy = Automatic

	column 'Hiring Manager ID'
		dataType: string
		summarizeBy: none
		sourceColumn: HiringManagerID
		lineageTag: 20000008-0001-0001-0001-200000000011

		annotation SummarizationSetBy = Automatic

	column 'Salary Range Min'
		dataType: double
		summarizeBy: sum
		sourceColumn: SalaryRangeMin
		lineageTag: 20000008-0001-0001-0001-200000000012

		annotation SummarizationSetBy = Automatic

	column 'Salary Range Max'
		dataType: double
		summarizeBy: sum
		sourceColumn: SalaryRangeMax
		lineageTag: 20000008-0001-0001-0001-200000000013

		annotation SummarizationSetBy = Automatic

	column 'Time to Fill Days'
		dataType: int64
		summarizeBy: sum
		sourceColumn: TimeToFillDays
		lineageTag: 20000008-0001-0001-0001-200000000014

		annotation SummarizationSetBy = Automatic

	partition 'Recruitment' = entity
		mode: directLake
		schemaName: fact
		entityName: factrecruitment
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
